### PR TITLE
Conv2DDNN layer using cudnn

### PR DESCRIPTION
**Pull request by dimatura**
Hello, here's a first stab at the `cudnn`-based layer, as suggested in #90 . It works for me, and the mnist example works fine as well. But I haven't tested different versions of `border_mode` and `pad`. I have just noticed there is already another branch with a `cudnn`-based pooling layer already there. I guess they should be merged before further work? Not sure the best way to proceed.

### CODE REVIEW

**Comment by dimatura** [comment]
Actually I'm pretty sure there's something wrong in the `border_mode`/`pad` logic -- working on it now.

**Comment by benanne** [comment]
This looks great! It's good that you've mimicked the interface of `Conv2DCCLayer` where possible. Maybe we should call the submodule `dnn` instead of `cudnn` though, just to be consistent with Theano's naming convention.

Unfortunately this currently seems to break all tests on Travis because importing `theano.sandbox.cuda.dnn` fails when no GPU is present. I am having the same issue in #91 (which wraps `dnn_pool`, so it complements this work nicely).

I'm not certain of this, but it should be fine to import this whenever a GPU device is available, even if the cudnn library isn't (we should probably test this assumption).

Theano itself only imports theano.sandbox.cuda when `theano.config.device.startswith("gpu")`: https://github.com/Theano/Theano/blob/master/theano/__init__.py#L94
I guess we should do something similar here.

**Comment by benanne** [comment]
I added a check to ensure we're running on the GPU, and whether cudnn is available. This fixes it: https://github.com/benanne/Lasagne/commit/acabd27fd41dbab04c2e9353bc52a94e610a5570

Maybe I'll merge that into master and then you can rebase on top of it? Let me know if that's okay.

**Comment by dimatura** [comment]
Sounds good!

**Comment by benanne** [comment]
done :)

**Comment by dimatura** [comment]
Things seem to be ok except for the fact the example fails in travis, when the "dnn not available" exception is thrown. I guess there should be a special case for that, as with the pylearn2 import.

**Comment by benanne** [comment]
@dimatura on a somewhat unrelated note, are you using this code with cudnn R1 or R2? I'm having a hard time getting R2 to work with Theano: https://groups.google.com/forum/#!topic/theano-users/0dCxdDSKFjA

**Comment by dimatura** [comment]
@f0k Ah yeah, I did rebase but you're right, I probably  didn't do it the right way. I'll try the cherry picking. 
@benanne I am using cudnn R2 (it's the only one I've installed), and it has been somewhat flaky lately. I've been keeping up to date with theano master and recent commits have given me trouble that seems related to a series of commits for doing shape inference for some convolution configurations, but it's a different error than you get. I have a K40 and 340.29, for what it's worth.

**Comment by dimatura** [comment]
Ok, sorry for the delay. I think the cherry-picked branch looks sane, without the duplicate commits. Thanks @f0k for the git wisdom :)

**Comment by benanne** [comment]
Thanks! Sorry for the trouble :)

It looks like this contains both dnn.py and cudnn.py though, I think cudnn.py can just be deleted.

**Comment by dimatura** [comment]
Ah curses! Fixed.

**Comment by benanne** [comment]
Alright, looks good to me. I'll wait for Travis and then merge. At some point we'll want to add some tests for this, but it makes more sense to write tests for the regular `Conv2DLayer` first since a lot of them will be reusable for all the variants.

**Comment by dimatura** [comment]
I agree, I saw that there's no conv2d tests. I've had various problems with certain combinations of strides, pad sizes and so on - probably more Theano-related than Lasagne-related. Sometimes due to upstream problems, sometimes myself.

**Comment by benanne** [comment]
Looks like it's still trying to run the example test, which causes the Travis failure. We'll need to modify test_examples.py to skip it if cudnn is not available. Feel free to do that if you want, otherwise I'll probably have a look at it tomorrow.

**Comment by dimatura** [comment]
Added an exception for the cudnn error.

**Comment by benanne** [comment]
Sweet! Merging in 3... 2... 1...

**Pull request merged**
