### PR TITLE
change Conv2DLayer.get_output_shape to match Theano for border_mode='ful...

### LINKED ISSUE #154: error in output shape calculation for strided Conv2DLayer with border_mode='full'
Simple example:

        l_in = lasagne.layers.InputLayer(
            shape=(1, 1, 10, 10),
        )

        l_conv = lasagne.layers.Conv2DLayer(
            l_in,
            num_filters=1,
            filter_size=(3, 3),
            strides=(2,2),
            border_mode='full',
        )

`l_conv.get_output_shape()` gives (1, 1, 5, 5)
But `l_conv.get_output(x).shape` yields (1, 1, 6, 6)

### PR DESCRIPTION
**Pull request by ebenolson**
To fix #154, change the calculation of output shape in Conv2DLayer with `border_mode=='full'` to match [Theano](https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/conv.py#L252])

### CODE REVIEW

**Comment by benanne** [comment]
Thanks!

As  @f0k mentioned in #154, it's probably cleaner to use the 'nice' formula that's mentioned in the comments in the `ConvOp` Theano code that I linked. We have no real reason to resort to integer arithmetic here. Or if you'd prefer to keep the formulas as is, there should also be a comment explaining where the formulas come from, like in the Theano code. That way we'll still know what's going on here in six months :)

**Comment by ebenolson** [comment]
I think it's cleaner to use the same formula as in Theano, but I'll add some comments on the derivation. 

Correct me if I'm wrong, but I think there is a similar error for `border_mode=='same'`, it should be `(i + d - 1) // d`?

Conv1DLayer probably needs the same fix as well, should I do that here or make a separate PR?

**Comment by benanne** [comment]
Feel free to fix all of them :) Some tests for this would also be a welcome addition, but we can take care of this later if necessary.

**Comment by f0k** [comment]
> I think it's cleaner to use the same formula as in Theano

As you already found out, we have an additional border mode here. I think having three formulas of the tricky kind isn't too helpful. Wouldn't it be much easier to do something like (this is untested):
```python
filter_size = np.array(self.filter_size)
input_shape = np.array(input_shape)
strides = np.array(self.strides).astype(np.float)
if self.border_mode = 'full':
    padding = filter_size
elif self.border_mode = 'same':  # should have been 'half', in my opinion
    padding = filter_size // 2
elif self.border_mode = 'valid':
    padding = 0
output_size = np.ceil((input_shape[2:] + padding - filter_size) / strides).astype(np.int)
return (input_shape[0], self.num_filters) + tuple(output_size)
```
This should work for 1D, 2D, and 3D, so it could become a central helper function. And it would be easy to extend for the case of custom padding that will be added to Theano anyway (where `border_mode` is either an integer or a tuple of integers).

> Some tests for this would also be a welcome addition, but we can take care of this later if necessary.

+1! This would make sure the function does the right thing.

**Comment by ebenolson** [comment]
That seems to have a couple of bugs in it, but a helper function is probably the way to go. 

I think it's only tricky because of the integer round-up, but with a comment to explain that it seems cleaner to me than multiple casts and using numpy.

**Comment by f0k** [comment]
> That seems to have a couple of bugs in it

Yes, I guess so. I just wanted to illustrate the idea of using `border_mode` to set the padding and then use a common formula, rather than having a separate formula for each border mode (and then another one for custom padding when it's there). And the idea of having a single equation for each dimension, so the code can be shared between 1D, 2D, and 3D (whether it's using numpy, a list comprehension or a for loop is not crucial).

> I think it's only tricky because of the integer round-up, but with a comment to explain that it seems cleaner to me than multiple casts and using numpy.

Okay, I don't have a strong opinion on that, I'd welcome any solution that fixes the bug and is comprehensible :) Do you want to continue on that in this PR? Things left to do would be:
* [ ] also fix border_mode='same'
* [ ] fix the 1D and 3D case
* [ ] comment on the formula
* [ ] add tests (we can do that ourselves if needed)

**Comment by ebenolson** [comment]
Sure, I'm a little busy the next few days, but I should be able to do it by the weekend.

**Comment by benanne** [comment]
Awesome, thanks for contributing :)

**Comment by ebenolson** [comment]
Unfortunately, the tests I added show some new issues.

Currently the Theano-backed conv layer implements "same" by trimming a strided "full" convolution.
To get the proper output, instead it should first trim the convolution, then perform striding. 

The cuda-convnet version also has issues, but I'm less sure what's going on there.

**Comment by benanne** [comment]
```
instead it should first trim the convolution, then perform striding.
```

How does that work though? If I understood correctly that means you would compute a convolution with stride=1 and then throw away most of the result, which seems very wasteful.

The reason it's currently implemented the way it is, is to be able to do same convolutions with as little overhead as possible. Luckily the Theano convolution implementations are going to be cleaned up sometime soon ( https://github.com/Theano/Theano/issues/2505 ) so in the near future this 'hack' should no longer be necessary.

**Comment by ebenolson** [comment]
Yeah, I think raising `NotImplementedError

**Comment by benanne** [comment]
I see you always raise now for `border_mode='same'`, I was thinking it should only raise when `border_mode == 'same' and stride > 1`. But I guess there's something to be said for not implementing it at all, since the implementation is suboptimal. Anyway, so as not to break too many people's code, it would be great to have it working when the stride is 1, for now.

Once the Theano convolution interface has been cleaned up this will not be an issue anymore anyway, so I think that's the best solution in the meantime :)

**Comment by ebenolson** [comment]
Oops, fixed.

**Comment by f0k** [comment]
@benanne: I think you need to retrigger Travis, the build has stalled.

**Comment by benanne** [comment]
If we want to rename this let's create a separate issue / pull request for that, so as not to draw out this one :) I've restarted Travis.

**Comment by benanne** [comment]
This looks good to me, and Travis passes :) So unless there are any further comments I will merge this soon. It may take a few days because I'm currently abroad.

**Comment by benanne** [comment]
Merged, thanks again!

**Pull request merged**
