### PR TITLE
Split up layer tests into several modules

### PR DESCRIPTION
**Pull request by dnouri**
It's awkward, but here it is.

### CODE REVIEW

**Comment by benanne** [comment]
Good call. Why is it awkward?

**Comment by f0k** [comment]
+1 (can you upvote things on github or was that just gitlab? Anyway, thanks, that makes it a lot more convenient to handle.)

**Comment by benanne** [comment]
I'll go ahead and merge this but I'm still curious about why you think it's awkward :p

**Comment by dnouri** [comment]
Never mind, I guess it's not awkward (petty?) if you guys think it's useful.  :-)

**Pull request merged**
