### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by diogo149**
Changes:
- fix dnn imports in the examples
- cuda-convnet example didn't return output_layer
- the accuracy returned was float64, which caused problems when the warn_float64 theano flag is set

### CODE REVIEW

**Comment by benanne** [comment]
Thanks for this! We should have caught this sooner. In my defence, my laptop has a GT 540M so I can't run the dnn example on that :p 

Since the changes are fairly small and Travis passes, I'll go ahead and merge this.

**Comment by dnouri** [comment]
I wish this PR and others included fewer random changes to indentation.

**Comment by craffel** [comment]
> I wish this PR and others included fewer random changes to indentation.

This is why we need to enforce a style guide (starting, at least, with PEP-8).  Not to be pedantic, but all of these aesthetic code changes will disrupt the blame pretty heavily.

**Comment by benanne** [comment]
Agreed, this is something I haven't been paying enough attention to. But the PEP8 issue (#21) never came to a conclusion - we should take care of that first.

**Comment by dnouri** [comment]
Agree too.  Consider though that the indentation changes that went into this PR weren't even a PEP8 issue.  I'd say collaborators need to stop configuring their editor to randomly move parenthesis around, if that's what's happening.

**Pull request merged**
